"""services/models.py
Shared typed dataclasses and data models for Rukiya V2.
"""
from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class ChatMessage:
    """Normalized chat message across platforms (YouTube live chat, Discord, etc.)."""
    platform: str  # "youtube" or "discord"
    message_id: str
    user_id: Optional[str]  # Platform-specific unique ID (e.g. channel ID or Discord snowflake)
    username: str
    display_name: str
    text: str
    timestamp: float = field(default_factory=time.time)
    channel_id: Optional[str] = None
    video_id: Optional[str] = None
    is_owner: bool = False
    is_moderator: bool = False
    raw_event: Optional[Any] = None

    @property
    def author_repr(self) -> str:
        return self.display_name or self.username or "viewer"


@dataclass
class UserIdentity:
    """Resolved user identity linking platform and unique canonical ID."""
    canonical_id: str  # Format: "platform:user_id" (e.g. "youtube:UC123", "discord:456")
    platform: str
    user_id: str
    username: str
    display_name: str
    first_seen: float = field(default_factory=time.time)
    last_seen: float = field(default_factory=time.time)
    interaction_count: int = 0
    is_welcomed_in_stream: bool = False
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ResponseDecision:
    """Decision object produced by DecisionService determining if/how to respond."""
    should_respond: bool
    intent: str = "chatter"  # e.g., "greeting", "question", "compliment", "offtopic", "spam", "help"
    priority: float = 0.0  # 0.0 to 1.0
    response_mode: str = "personality"  # "personality", "fallback", "boundary", "ignore"
    memory_needed: bool = False
    reason: str = ""
    extra: Dict[str, Any] = field(default_factory=dict)


@dataclass
class GeneratedResponse:
    """Output generated by AIService or fallback responder."""
    text: str
    confidence: Optional[float] = None
    used_memory: bool = False
    latency_ms: float = 0.0
    tokens_used: int = 0
    model: str = ""
    is_fallback: bool = False


@dataclass
class SafetyResult:
    """Result of input or output safety validation."""
    allowed: bool
    reason: str = ""
    sanitized_text: str = ""
    risk_score: float = 0.0
    flagged_patterns: List[str] = field(default_factory=list)


@dataclass
class MemoryEntry:
    """Individual atomic fact or preference in persistent or stream memory."""
    key: str
    value: str
    confidence: float = 0.9
    source: str = "explicit_statement"  # e.g., "explicit_statement", "inferred", "system"
    created_at: float = field(default_factory=time.time)
    updated_at: float = field(default_factory=time.time)
    last_used_at: float = field(default_factory=time.time)
    usage_count: int = 1
    session_id: Optional[str] = None


@dataclass
class StreamSession:
    """Livestream session tracking for temporary memory scoping."""
    session_id: str
    video_id: str
    started_at: float = field(default_factory=time.time)
    ended_at: Optional[float] = None
    is_active: bool = True
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class RateLimitResult:
    """Result of checking a rate limiter bucket."""
    allowed: bool
    wait_time: float = 0.0
    bucket_name: str = ""
